=== erazamus/XML101-2.2.4-introduction-to-xml-training/DTDs/Solutions/BusinessLetter.dtd
<!--root element-->
<!ELEMENT BusinessLetter (Head, Body, Foot)>

<!--head elements and attributes-->
<!ELEMENT Head (SendDate, Recipient)>
<!ELEMENT Recipient (Name, Company, Address)>
<!ELEMENT Name (FirstName, LastName)>
<!ATTLIST Name
  Title CDATA #IMPLIED>
<!ELEMENT Address (Company*, Street, City, State, Zip, Country)>

<!--body elements-->
<!ELEMENT Body (List, Para+)>
<!ELEMENT Para (#PCDATA | Person | Phone | Email)*>
<!ELEMENT List (Heading, ListItem+)>
<!ELEMENT Person (Name, Address)>

<!--foot elements-->
<!ELEMENT Foot (Closing)>
<!ELEMENT Closing (Name, JobTitle)>

<!--simple text elements-->
<!ELEMENT SendDate (#PCDATA)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Company (#PCDATA)>
<!ELEMENT Heading (#PCDATA)>
<!ELEMENT ListItem (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Zip (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT JobTitle (#PCDATA)>

=== erazamus/XML101-2.2.4-introduction-to-xml-training/DTDs/Solutions/BusinessLetter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BusinessLetter SYSTEM "BusinessLetter.dtd">
<BusinessLetter>
  <Head>
    <SendDate>September 29, 2024</SendDate>
    <Recipient>
      <Name Title="Mr.">
        <FirstName>Joshua</FirstName>
        <LastName>Woodlock</LastName>
      </Name>
      <Company>Woodlock &amp; Woodlock</Company>
      <Address>
        <Street>291 Broadway Ave.</Street>
        <City>New York</City>
        <State>NY</State>
        <Zip>10007</Zip>
        <Country>United States</Country>
      </Address>
    </Recipient>
  </Head>
  <Body>
    <List>
      <Heading>Along with this letter, I have enclosed the following items:</Heading>
      <ListItem>two original, execution copies of the Webucator Master Services Agreement</ListItem>
      <ListItem>two original, execution copies of the Webucator Premier Support for Developers Services Description between Woodlock &amp; Woodlock and Webucator, Inc.</ListItem>
    </List>
    <Para>Please sign and return all four original, execution copies to me at your
earliest convenience.  Upon receipt of the executed copies, we will
immediately return a fully executed, original copy of both agreements to you.</Para>
    <Para>lease send all four original, execution copies to my attention as follows:
  Webucator, Inc.
    4933 Jamesville Rd.
    Jamesville, NY 13078  USA
    Attn: Bill Smith
    </Para>
    <Para>If you have any questions, feel free to call me at 800-555-1000 x123 or e-mail me at bsmith@webucator.com.</Para>
  </Body>
  <Foot>
    <Closing>
      <Name>
        <FirstName>Bill</FirstName>
        <LastName>Smith</LastName>
      </Name>
      <JobTitle>VP, Operations</JobTitle>
    </Closing>
  </Foot>
</BusinessLetter>
